language: node_js
node_js:
  - "node"
cache:
  directories:
    - node_modules
warnings_are_errors: false
install:
  - npm install
script:
  - npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: "jNBYqUsOO2w54qacJAbTha0x9DMaVAMkf0eFH3rkaoaUZ9aIPmYSB9ialqldNFgBx81kgpuV+WQthTNKSwqtaURi/6J3owckcKcb3TS8j2mZlAZdnPGRWSHRCjy7w2QJ5C8qlhE0jBMfwjOYJ23c1V/YK6c+VfjFd+tIihyptK2pzSTSf9qnOXODjjSjPuo5rPkm0UAZLUOa3+z75OjjyInYKrtLMKukpVAHBfRqNJ0CU6/vcecMUN9ga0y5WKE80Abe1GpydWHStu4Jaqb6GQYTtvJ5OfEFWKwznsmGtxXdoEdJUiI4QoM79CtbUzLD4uZv+Kwvmc5NolwX66wb8Tf/MKdJuQlRnY9UDBrTdHcSgv0/jGCcrYNONs403S6OaXWJ5dZM6IcrLJ/PFO4IXhfddZqs4+CInbPZ/e+hstHcppjYM/Jj3MHGn1KLwH8X7On6O05KOs9aKNSo2YutSytCU+HSY0fRhMW2iYKyqoR1ycyphg2aRQC7zl5d4HIhKKemvi/ajLP8ds72UUglhTgEGUQvNyLxZNpUeezpNQsXz5J8PCHjehKCFd+QTDeQrHAY1S79SBSQuVnm8wGnkgknsBQl6uBEzxkS5Ow/RyYvcApIh4fykNt5Nbvk8k80c1CV+JYsQX788cFgFo168X+ugPxLXwhXTVwI+9CowC4="

